language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-19mode
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: openjdk6
    - rvm: rbx-19mode
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: openjdk6
