language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - jruby-20mode
  - rbx
  - rbx-2
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
matrix:
  exclude:
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.2
      jdk: openjdk7
    - rvm: 1.9.2
      jdk: openjdk6
    - rvm: rbx
      jdk: openjdk7
    - rvm: rbx
      jdk: openjdk6
    - rvm: rbx-2
      jdk: openjdk7
    - rvm: rbx-2
      jdk: openjdk6
